apiVersion: apps/v1
kind: Deployment
metadata:
  name: agri-app
  namespace: default
  labels:
    app: agri-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agri-app
  template:
    metadata:
      labels:
        app: agri-app
    spec:
      containers:
        - name: agri-app
          image: fayzullayev7505/agri-app:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
